version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: got_it_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Janjao2004***"
      MYSQL_DATABASE: "got_it"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: