FROM python:3.11-slim

# Define o diretório de trabalho dentro do container
WORKDIR /code

# Evita que o Python escreva arquivos .pyc e bufferize logs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copia e instala as dependências
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copia todo o código da pasta app para dentro do container
COPY ./app /code/app

# Expõe a porta que o FastAPI vai rodar
EXPOSE 8000

# Comando para iniciar a aplicação
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]